<a href="https://colab.research.google.com/github/Parnani/Machine-Learning-/blob/main/Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf
import numpy as np


In [ ]:
string =  tf.Variable("this is a string", tf.string) #tf.string is a datatype
number = tf.Variable(324, tf.int16)
floating = tf.Variable(3.567,tf.float64)

word for rank is degree, these terms simply mean the no. of dimensions involved in the tensor.

In [ ]:
#@title Default title text
rank1_tensor = tf.Variable(["Test", "Ok", "Tim"], tf.string)  #rank=1, as 1 list and array is there
rank2_tensor = tf.Variable([["test", "ok"],["test","yes"]],tf.string) #2 list are there, so rank =2
rank3_tensor = tf.Variable([["test", "ok","yes"],["test","yes","ok"]],tf.string)
rank4_tensor = tf.Variable([["test", "ok","yes"],["test","yes","ok"],["ok","yes","ok"]],tf.string)
#rank is the deepest level in a list

In [ ]:

tf.rank(rank4_tensor)

#rank1 = numpy =1(means the rank is 1)
#rank2 = numpy =2(means the rank is 2)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [ ]:
rank4_tensor.shape # 3 list and each list has 3 elements
rank3_tensor.shape

TensorShape([2, 3])

In [ ]:
tensor1=tf.ones([1,2,3])
print(tensor1)
#1 interior list, 2lists inside bigger list and 3 elemnets in the list
#RESHAPE
tensor2 = tf.reshape(tensor1 , [2,3,1])
print(tensor2)
#reshaping existing tensor1 to {2,3,1},2 outer list, with 2 list inside 1 outer list , and each list contains 1 element
tensor3 = tf. reshape(tensor1,[3,-1])
#-1 tells the tensor to calculate the size of the dimension in that place
#this will reshape the tensor to [3,2]

tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]], shape=(1, 2, 3), dtype=float32)
tf.Tensor(
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]], shape=(2, 3, 1), dtype=float32)


In [ ]:
with tf.Session() as sess:
  tensor.eval()

AttributeError: ignored

In [ ]:
%tensorflow_version 2.x
import tensorflow as tf
print(tf.version)

t=tf.zeros([5,5,5,5])
print(t)
t = tf.reshape(t,[625])
print(t)
t = tf.reshape(t,[125,-1])
print(t)

Colab only includes TensorFlow 2.x; %tensorflow_version has no effect.
<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.8/dist-packages/tensorflow/_api/v2/version/__init__.py'>
tf.Tensor(
[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]